-- MySQL Script generated by MySQL Workbench
-- Wed May 13 19:05:42 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`airports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`airports` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `airport_name` VARCHAR(45) NOT NULL,
  `airport_location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`planes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`planes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) NOT NULL,
  `number_of_engines` INT NULL,
  `number_of_seats` INT NULL,
  `airport_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_planes_airports_idx` (`airport_id` ASC) VISIBLE,
  CONSTRAINT `fk_planes_airports`
    FOREIGN KEY (`airport_id`)
    REFERENCES `mydb`.`airports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employees` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `salary` INT NOT NULL,
  `airport_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_employees_airports1_idx` (`airport_id` ASC) VISIBLE,
  CONSTRAINT `fk_employees_airports1`
    FOREIGN KEY (`airport_id`)
    REFERENCES `mydb`.`airports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`guests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`guests` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `passport_number` INT NOT NULL,
  `plane_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_guests_planes1_idx` (`plane_id` ASC) VISIBLE,
  CONSTRAINT `fk_guests_planes1`
    FOREIGN KEY (`plane_id`)
    REFERENCES `mydb`.`planes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bookings` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `booking_number` INT NOT NULL,
  `booking_date` DATE NOT NULL,
  `airport_id` BIGINT UNSIGNED NOT NULL,
  `guest_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_bookings_airports1_idx` (`airport_id` ASC) VISIBLE,
  INDEX `fk_bookings_guests1_idx` (`guest_id` ASC) VISIBLE,
  CONSTRAINT `fk_bookings_airports1`
    FOREIGN KEY (`airport_id`)
    REFERENCES `mydb`.`airports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookings_guests1`
    FOREIGN KEY (`guest_id`)
    REFERENCES `mydb`.`guests` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lunch_menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lunch_menus` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `plane_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_lunch_menus_planes1_idx` (`plane_id` ASC) VISIBLE,
  CONSTRAINT `fk_lunch_menus_planes1`
    FOREIGN KEY (`plane_id`)
    REFERENCES `mydb`.`planes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `calories` INT NOT NULL,
  `price` INT NOT NULL,
  `fresh` TINYINT NOT NULL,
  `lunch_menu_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_products_lunch_menus1_idx` (`lunch_menu_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_lunch_menus1`
    FOREIGN KEY (`lunch_menu_id`)
    REFERENCES `mydb`.`lunch_menus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`card_payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`card_payments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `card_number` INT NOT NULL,
  `payment_number` INT NOT NULL,
  `payment_amount` INT NOT NULL,
  `payment_date` DATE NOT NULL,
  `booking_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_card_payments_bookings1_idx` (`booking_id` ASC) VISIBLE,
  CONSTRAINT `fk_card_payments_bookings1`
    FOREIGN KEY (`booking_id`)
    REFERENCES `mydb`.`bookings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
